version: '3.11'
services:
  imagem: drupalci/webdriver-chromedriver
  bot:
    container_name: av-container
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    pull_policy: build