version: '3'
services:
  selenium:
    image: selenium/standalone-chrome:112.0
    container_name: selenium-chrome
    ports:
      - "4445:4444"  # Mapeando o serviço Selenium para a porta 4445 do host

  app:
    build: .
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=selenium
    links:
      - selenium
