version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playwright_container
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "main.py"]
