version: '3.8'

services:
  selenium-chrome-1:
    image: selenium/standalone-chrome:112.0
    ports:
      - "4444:4444"
    networks:
      - selenium_network

  selenium-chrome-2:
    image: selenium/standalone-chrome:112.0
    ports:
      - "4445:4444"
    networks:
      - selenium_network

networks:
  selenium_network:
    driver: bridge
