version: '3.8'

services:
  bot:
    image: ultrafunk/undetected-chromedriver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "main.py"]
    restart: always

  undetected-chromedriver:
    image: ultrafunk/undetected-chromedriver
    restart: always
