version: '3'

services:
  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  my-django-project:
    build: .
    depends_on:
      - selenium-chrome
    network_mode: "host"
