version: '3'
services:
  selenium:
    image: selenium/standalone-chrome:112.0
    container_name: selenium-chrome
    ports:
      - "4444:4444"

  app:
    build: .
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=selenium
    links:
      - selenium
